"""Nothing tracked, generated or rendered may leak private information.

This is a test rather than a checklist so that it runs on every change.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import pytest

from fluorescence_inference import reporting as rp

ROOT = Path(__file__).resolve().parents[1]

FORBIDDEN = {
    "windows absolute path": re.compile(r"[A-Za-z]:\\{1,2}Users", re.I),
    "posix home path": re.compile(r"/(?:home|Users)/[A-Za-z0-9._-]+"),
    "email address": re.compile(r"[\w.+-]+@[\w-]+\.[\w.]{2,}"),
    "mit internal host": re.compile(r"\b(?:\w+\.)?mit\.edu\b", re.I),
    # assembled from parts rather than written out: the literal strings are
    # themselves lab-identifying, and this file is tracked
    "shared data root": re.compile("MIT" + r"\s+" + "Dropbox", re.I),
    "lab account name": re.compile("Quan" + "tum" + r"\s+" + "1", re.I),
}

# Attribution rules: only Peiran Niu, no tooling credited anywhere.
ATTRIBUTION = re.compile(
    r"claude|anthropic|openai|chatgpt|codex|copilot|co-authored-by|"
    r"generated by ai|language model", re.I)

TEXT_SUFFIXES = {".py", ".md", ".toml", ".yaml", ".yml", ".json", ".cfg",
                 ".txt", ".ipynb", ".gitignore", ""}
SKIP_DIRS = {".git", ".venv", "__pycache__", ".pytest_cache", "Experiment-Data",
             "data", "reports", ".ipynb_checkpoints", "assets"}


def tracked_text_files() -> list[Path]:
    """Every tracked text file except this one, which defines the patterns."""
    out: list[Path] = []
    here = Path(__file__).resolve()
    for p in ROOT.rglob("*"):
        if not p.is_file() or p.resolve() == here:
            continue
        if any(part in SKIP_DIRS for part in p.relative_to(ROOT).parts):
            continue
        if p.suffix.lower() in TEXT_SUFFIXES or p.name == ".gitignore":
            out.append(p)
    return out


@pytest.mark.parametrize("name,pattern", sorted(FORBIDDEN.items()))
def test_no_private_strings_in_tracked_files(name, pattern):
    hits = []
    for p in tracked_text_files():
        text = p.read_text(encoding="utf-8", errors="replace")
        for m in pattern.finditer(text):
            line = text[:m.start()].count("\n") + 1
            hits.append(f"{p.relative_to(ROOT).as_posix()}:{line}")
    assert not hits, f"{name} found in: {hits}"


def test_no_tool_or_model_attribution_in_tracked_files():
    hits = []
    for p in tracked_text_files():
        text = p.read_text(encoding="utf-8", errors="replace")
        for m in ATTRIBUTION.finditer(text):
            line = text[:m.start()].count("\n") + 1
            hits.append(f"{p.relative_to(ROOT).as_posix()}:{line} -> {m.group(0)}")
    assert not hits, f"unwanted attribution: {hits}"


def test_package_metadata_names_only_the_author():
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert 'authors = [{ name = "Peiran Niu" }]' in text
    assert 'maintainers = [{ name = "Peiran Niu" }]' in text
    assert text.count("name = ") == 3, "one project name, one author, one maintainer"


def test_gitignore_excludes_raw_and_processed_data():
    text = (ROOT / ".gitignore").read_text(encoding="utf-8")
    for entry in ("Experiment-Data/", "data/processed/", "reports/qc/",
                  "configs/local.toml"):
        assert entry in text, f"{entry} must be gitignored"


def test_generated_metadata_redacts_paths():
    meta = ROOT / "data" / "processed" / "paired_100ms_v0.meta.json"
    if not meta.exists():
        pytest.skip("processed dataset unavailable")
    blob = json.loads(meta.read_text(encoding="utf-8"))
    paths = blob["provenance"]["config"]["paths"]
    assert set(paths.values()) <= {"<configured:present>", "<configured:missing>"}
    text = json.dumps(blob)
    for name, pattern in FORBIDDEN.items():
        assert not pattern.search(text), f"{name} leaked into the metadata sidecar"


def test_asset_metadata_is_clean():
    meta = ROOT / "assets" / "readme" / "asset_metadata.json"
    if not meta.exists():
        pytest.skip("README assets not generated")
    text = meta.read_text(encoding="utf-8")
    for name, pattern in FORBIDDEN.items():
        assert not pattern.search(text), f"{name} leaked into the asset metadata"
    assert not ATTRIBUTION.search(text)


def test_figure_text_guard_rejects_private_strings():
    # assembled at runtime so a repository-wide grep for private strings stays
    # clean; a literal example here would be indistinguishable from a real leak
    drive = "C" + ":" + "\\" + "Users" + "\\someone\\run.h5"
    posix = "/" + "home" + "/someone/run.h5"
    mail = "someone" + "@" + "example.edu"
    inst = "x" + "@" + "mit" + "." + "edu"
    for bad in (drive, posix, mail, f"contact me at {inst}"):
        with pytest.raises(ValueError, match="refusing to render"):
            rp.assert_public_safe(bad, "unit test")


def test_figure_text_guard_allows_ordinary_captions():
    rp.assert_public_safe("100 shots, 2 frames per shot, 100 ms exposure")
    rp.assert_public_safe("Background-corrected ROI count (camera counts)")


def test_git_identity_is_configured_when_this_is_a_repo():
    """Commits must be attributed to the author, via the private noreply alias.

    The address itself is checked by shape rather than written out, so that a
    grep for addresses over this repository finds nothing.
    """
    if not (ROOT / ".git").exists():
        pytest.skip("not a git repository yet")

    def cfg(key: str) -> str:
        r = subprocess.run(["git", "config", "--local", "--get", key], cwd=ROOT,
                           capture_output=True, text=True)
        return r.stdout.strip()

    assert cfg("user.name") == "Peiran Niu"
    address = cfg("user.email")
    assert re.fullmatch(r"\d+\+[\w-]+@users\.noreply\.github\.com", address), (
        "commit identity must be the private GitHub noreply alias")


def test_no_attribution_in_recent_commit_messages():
    if not (ROOT / ".git").exists():
        pytest.skip("not a git repository yet")
    log = subprocess.run(["git", "log", "--format=%H%n%B", "-20"], cwd=ROOT,
                         capture_output=True, text=True)
    if log.returncode != 0 or not log.stdout.strip():
        pytest.skip("no commits yet")
    hit = ATTRIBUTION.search(log.stdout)
    assert not hit, f"commit message contains attribution: {hit.group(0)!r}"
